swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  '/media/{mediaId}':
    get:
      description: Get specific post
      parameters:
        - in: path
          name: mediaId
          required: true
          type: string
      responses:
        '200':
          description: succesful
          schema:
            $ref: '#/definitions/PageResponse'
    put:
      parameters:
        - name: mediaId
          in: path
          description: PK of post
          required: true
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/PostParams'
      responses:
        '200':
          description: succesful
    delete:
      parameters:
        - name: mediaId
          in: path
          description: PK of post
          required: true
          type: string
      responses:
        '200':
          description: succesful
  /media/create:
    post:
      description: Upload media
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PostParams'
      responses:
        '200':
          description: succesful
definitions:
  PostParams:
    type: object
    properties:
      title:
        type: string
      image:
        type: string
      content:
        type: string
      name:
        type: string
  PageResponse:
    type: object
    properties:
      data:
        type: string
      file:
        type: object
        properties:
          schema:
            $ref: '#/definitions/FilePath'
  FilePath:
    type: object
    properties:
      path:
        type: string
      id:
        type: string

